apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrain-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terrain
  template:
    metadata:
      labels:
        app: terrain
    spec:
      containers:
        - name: web
          image: php:8.2-apache
          ports:
            - containerPort: 8080
            - containerPort: 22
          volumeMounts:
            - name: app-volume
              mountPath: /var/www/html
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Hello@123
            - name: MYSQL_DATABASE
              value: sokmasterly_db
          ports:
            - containerPort: 3306
      volumes:
        - name: app-volume
          emptyDir: {}
